### ISSUE TITLE
Having problems starting django

### ISSUE THREAD

**Issue by sysingleton** [lauramayol/crypto_signal#14]
Still having problems if  getting environment up and running. I had to explicitly call python3.6 . 

(env) xaun@BLOCKY:~/crypto_signal$ /usr/bin/python3.6 crypto_signal/manage.py runserver
Traceback (most recent call last):
  File "crypto_signal/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "crypto_signal/manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by sysingleton** [comment]
Not sure what happened but I went over the install again and was able to get it working .
