### ISSUE TITLE
Problem Starting Local Instance

### ISSUE THREAD

**Issue by sysingleton** [lauramayol/crypto_signal#7]
Worked my way through the README.md to line 8 Run development server
python crypto_signal/manage.py runserver  

When I run that line I get the following error. Not sure how to resolve the issue. 

(env) xaun@BLOCKY:~/crypto_signal$ python crypto_signal/manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0c3f9cf0d0>
Traceback (most recent call last):
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/xaun/crypto_signal/env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/xaun/crypto_signal/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/xaun/crypto_signal/crypto_signal/crypto_track/models.py", line 25
    return f"{self.date}"
                        ^
SyntaxError: invalid syntax

**Comment by martin-martin** [comment]
Hi @sysingelton - the reason is that you are using python 3.5 but the project uses g-strings for string formatting, which requires python >= 3.6

So if you update your python version you'll be fine!
